# Generated by Django 4.1.3 on 2022-12-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('artista', models.CharField(max_length=70)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(max_length=70)),
                ('puntaje', models.FloatField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('autor', models.CharField(max_length=70)),
                ('año', models.IntegerField()),
                ('genero', models.CharField(max_length=70)),
                ('puntaje', models.FloatField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pinturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('artista', models.CharField(max_length=70)),
                ('año', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
