# Generated by Django 4.1.3 on 2023-01-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArte', '0005_pinturas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='discos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='discos/'),
        ),
        migrations.AddField(
            model_name='libros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
        migrations.AlterField(
            model_name='pinturas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pinturas/'),
        ),
    ]
