# Generated by Django 4.1.3 on 2023-01-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppArte', '0006_discos_imagen_libros_imagen_alter_pinturas_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinturas',
            old_name='imagen',
            new_name='foto',
        ),
    ]
