# Generated by Django 4.1.3 on 2023-01-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppArte', '0007_rename_imagen_pinturas_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='imagen',
            new_name='foto',
        ),
    ]
