# Generated by Django 4.1.3 on 2023-01-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppArte', '0008_rename_imagen_libros_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='foto',
            new_name='foto2',
        ),
    ]
